name: Exiled Dev CI

on:
  push:
    branches:
      - dev
      - workflow
  pull_request:
    branches:
      - dev
  workflow_dispatch:

env:
  EXILED_REFERENCES_URL: https://misaka-zerotwo.github.io/SL-References/Dev.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References
  EXILED_DLL_ARCHIVER_URL: https://github.com/Exiled-Team/EXILED-DLL-Archiver/releases/download/v1.3/EXILED-DLL-Archiver.exe

jobs:

  build:

    runs-on: self-hosted
    # Prevent double running for push & pull_request events from the main repo
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'Exiled-Team/Exiled'

    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master

    - uses: actions/checkout@v2.3.4
    
    - name: Get references
      shell: powershell
      run: |
        Invoke-WebRequest -Uri ${{ env.EXILED_DLL_ARCHIVER_URL }} -OutFile ${{ github.workspace }}/EXILED-DLL-Archiver.exe
    
    - name: Get references
      shell: powershell
      run: |
        Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
        Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}

    - name: Build
      env:
        EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
      shell: powershell
      run: |
        ./build.ps1 -BuildNuGet
        $File = (Get-ChildItem -Path . -Include 'EXILED.*.nupkg' -Recurse).Name
        Out-File -FilePath ${{ github.env }}
    
    - name: Move Files
      shell: powershell
      run: ./moveFile.ps1

    - name: Run archiver
      run: ./bin/Release/EXILED-DLL-Archiver.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Exiled.tar.gz
        path: bin/Release/Exiled.tar.gz

    - name: Upload nuget package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PackageFile }}
        path: ${{ env.PackageFile }}
