name: Publish Exiled Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: docs
          git-user: GithubPages
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
